### ISSUE TITLE
Bug: Panic if files directory does not exist

### ISSUE THREAD

**Issue by bomgar** [comtrya/comtrya#246]
**Description**
If I don't have a files directory I get a panic without a meaningful error message

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/actions/file/mod.rs:20:14
```
`-v` doesn't help either

**Steps to reproduce**
Move files direcotry

**Expected behaviour**
Useful error message

**Environment**
- OS Linux
- Version: `0.7.4`

**Comment by bomgar** [comment]
```
» comtrya  .
 INFO manifest_run{manifest="install"}: Nothing to be done to reconcile manifest
 INFO manifest_run{manifest="install"}: Completed
14:33:06 /tmp/demo
» mv files files2
14:33:12 /tmp/demo
» comtrya  .
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/actions/file/mod.rs:20:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`No such file or directory` this should state which file or directory is missing
