### ISSUE TITLE
Bug: `binary.github` panic on x64

### ISSUE THREAD

**Issue by bavarianbidi** [comtrya/comtrya#382]
**Description**
Using the latest released version of comtrya (`0.8.7`) panics when to use the `binary.github` action.

**Steps to reproduce**
Step by step explanation. Please add the output of with `-vvv` flag enabled (be careful not to include any secrets from your config).

Use the latest released version of comtrya for linux x64 (no matter if gnu or musl) and run `comtry apply` on a manifest where the `binary.github` action is getting used (e.g. the example from this repo - https://github.com/comtrya/comtrya/blob/main/examples/binary/github.yaml)

**Expected behaviour**

comtry should download and install the defined binary

**Environment**
- OS: Linux badfisch 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Version: 0.8.7

**Additional information**

```
RUST_BACKTRACE=1 ./comtrya-x86_64-unknown-linux-gnu apply
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-0.4.13/src/buffer/service.rs:76:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: tokio::task::spawn::spawn
   3: tower::buffer::service::Buffer<T,Request>::new
   4: octocrab::OctocrabBuilder<octocrab::NoSvc,octocrab::DefaultOctocrabBuilderConfig,octocrab::NoAuth,octocrab::NotLayerReady>::build
   5: core::ops::function::FnOnce::call_once
   6: once_cell::imp::OnceCell<T>::initialize::{{closure}}
   7: once_cell::imp::initialize_or_wait
   8: once_cell::imp::OnceCell<T>::initialize
   9: octocrab::instance
  10: <comtrya_lib::actions::binary::github::BinaryGitHub as comtrya_lib::actions::Action>::plan
  11: <comtrya_lib::actions::ConditionalVariantAction<T> as comtrya_lib::actions::Action>::plan
  12: <comtrya::commands::apply::Apply as comtrya::commands::ComtryaCommand>::execute::{{closure}}
  13: <comtrya::commands::apply::Apply as comtrya::commands::ComtryaCommand>::execute
  14: comtrya::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by martintc** [comment]
Could you try to reproduce this error on your machine with the new v0.8.8 release? I believe @icepuma merged in something that may address this. If it doesn't we can take a closer look.

For reference for anyone, I don't have this issue on macos aarm64. So if it still persists in v0.8.8, it may be linux platform specific.

**Comment by bavarianbidi** [comment]
Thanks, `v0.8.8` works fine
